version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:21.0  # Official Node.js CircleCI image
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
